export const strings = {
  english: {
    greeting_morning: 'Good morning',
    greeting_afternoon: 'Good afternoon',
    greeting_evening: 'Good evening',
    app_name: 'MindBridge AI',
    private: 'Private',
    quick_actions: 'QUICK ACTIONS',
    chat: 'Chat',
    mood: 'Mood',
    help: 'Help',
    daily_checkin: 'Daily Check-in',
    checkin_desc: 'Have you logged your mood today? Just 2 minutes!',
    checkin_btn: 'Check in now →',
    tip_title: 'Tip of the day',
    tip_desc: '5 minutes deep breathing reduces anxiety by 40%. Try it!',
    day_streak: 'Day Streak',
    avg_mood: 'Avg Mood',
    chats: 'Chats',
    quote: '"Your feelings are valid — you are not alone"',
    new: 'NEW',
    home: 'Home',
    profile: 'Profile',
    chat_greeting: "Hello! I'm your MindBridge AI companion. How are you feeling today? 😊",
    type_here: 'Type here...',
    online: 'Online',
    voice_on: 'Voice ON',
    mood_title: 'Mood Tracker',
    mood_sub: 'How are you feeling today?',
    todays_mood: "Today's Mood",
    save_mood: 'Save Mood',
    saved: '✓ Saved',
    last_7: 'Last 7 Days',
    talk_ai: 'Talk to MindBridge AI',
    great: 'Great', good: 'Good', okay: 'Okay', low: 'Low', bad: 'Bad',
    insight_great: 'Your week has been fantastic! 🌟',
    insight_ok: 'This week was balanced. Keep going! 💪',
    insight_low: 'The last few days were tough. Want to talk? 💙',
    insight_start: 'Start tracking your mood today! 😊',
    crisis_title: 'You Are Not Alone',
    crisis_sub: 'Asking for help is strength, not weakness.',
    breathing: 'Quick Breathing Exercise',
    breathing_desc: '4 sec inhale → 4 sec hold → 4 sec exhale. Repeat 3 times.',
    talk_btn: 'Talk to AI',
    helplines: 'Helplines — Free & Confidential',
    courage: '"Your feelings are valid. Asking for help takes courage!"',
    language_label: 'Language',
    user_type: 'User Type',
    save_profile: 'Save Profile',
    settings: 'Settings',
    daily_reminder: 'Daily Reminders',
    reminder_desc: 'Morning & Evening check-in',
    anonymous: 'Anonymous Mode',
    anonymous_desc: 'Use without revealing your identity',
    care_network: 'Care Network',
    care_desc: 'This person gets an alert during a crisis. Your permission only!',
    care_name: 'Contact name (e.g. Mom)',
    care_phone: 'Phone number',
    add_contact: '+ Add Contact',
    about: 'About',
    version: 'App Version',
    made_with: 'Made with',
    privacy: 'Privacy',
    test_notif: 'Test Notification',
    reset_app: 'Reset App',
    reset_confirm: 'All data will be deleted. Are you sure?',
    saved_success: 'Profile updated successfully!',
    remove: 'Remove',
    done: 'Done ✓',
    change: 'Change →',
  },

  tamil: {
    greeting_morning: 'காலை வணக்கம்',
    greeting_afternoon: 'மதிய வணக்கம்',
    greeting_evening: 'மாலை வணக்கம்',
    app_name: 'மைண்ட்பிரிட்ஜ் AI',
    private: 'தனிப்பட்டது',
    quick_actions: 'விரைவு செயல்கள்',
    chat: 'பேசு',
    mood: 'மனநிலை',
    help: 'உதவி',
    daily_checkin: 'தினசரி சரிபார்ப்பு',
    checkin_desc: 'இன்னைக்கு mood log பண்ணினியா? 2 minutes மட்டும்!',
    checkin_btn: 'இப்போவே சரிபார் →',
    tip_title: 'இன்றைய டிப்ஸ்',
    tip_desc: '5 நிமிட ஆழ்ந்த மூச்சு — கவலை 40% குறையும். Try பண்ணு!',
    day_streak: 'நாள் தொடர்',
    avg_mood: 'சராசரி மனநிலை',
    chats: 'உரையாடல்கள்',
    quote: '"உன்னோட feelings valid — நீ alone இல்ல"',
    new: 'புதிய',
    home: 'முகப்பு',
    profile: 'சுயவிவரம்',
    chat_greeting: 'வணக்கம்! நான் உன் MindBridge AI companion. இன்னைக்கு எப்படி இருக்க? 😊',
    type_here: 'இங்கே தட்டச்சு செய்யவும்...',
    online: 'நிகழ்நேரம்',
    voice_on: 'குரல் இயக்கம்',
    mood_title: 'மனநிலை கண்காணிப்பு',
    mood_sub: 'இன்னைக்கு எப்படி இருக்க?',
    todays_mood: 'இன்றைய மனநிலை',
    save_mood: 'சேமி',
    saved: '✓ சேமிக்கப்பட்டது',
    last_7: 'கடந்த 7 நாட்கள்',
    talk_ai: 'AI கிட்ட பேசு',
    great: 'அருமை', good: 'நல்லா', okay: 'சரி', low: 'கொஞ்சம்', bad: 'கஷ்டம்',
    insight_great: 'உன் week fantastic-ஆ இருக்கு! 🌟',
    insight_ok: 'இந்த week balanced-ஆ இருந்துச்சு. தொடர்ந்து போ! 💪',
    insight_low: 'கடந்த சில நாள் கஷ்டமா இருந்துச்சு. பேசலாமா? 💙',
    insight_start: 'இன்னைக்கே mood track பண்ண ஆரம்பிக்கலாம்! 😊',
    crisis_title: 'நீ தனியா இல்ல',
    crisis_sub: 'உதவி கேக்குறது தைரியம் — பலவீனம் இல்ல.',
    breathing: 'விரைவு மூச்சுப் பயிற்சி',
    breathing_desc: '4 sec மூச்சு இழு → 4 sec வை → 4 sec வெளியே விடு. 3 முறை செய்.',
    talk_btn: 'AI கிட்ட பேசு',
    helplines: 'உதவி எண்கள் — இலவசம் & ரகசியம்',
    courage: '"உன்னோட feelings valid. உதவி கேக்குறது தைரியம்!"',
    language_label: 'மொழி',
    user_type: 'பயனர் வகை',
    save_profile: 'சுயவிவரம் சேமி',
    settings: 'அமைப்புகள்',
    daily_reminder: 'தினசரி நினைவூட்டல்',
    reminder_desc: 'காலை & மாலை சரிபார்ப்பு',
    anonymous: 'அநாமதேய முறை',
    anonymous_desc: 'யாருக்கும் தெரியாம use பண்ணு',
    care_network: 'பராமரிப்பு நெட்வொர்க்',
    care_desc: 'நெருக்கடி நேரத்தில் இவருக்கு alert போகும். உன் அனுமதி மட்டும்!',
    care_name: 'தொடர்பு பெயர் (எ.கா. அம்மா)',
    care_phone: 'தொலைபேசி எண்',
    add_contact: '+ தொடர்பு சேர்',
    about: 'பற்றி',
    version: 'பதிப்பு',
    made_with: 'உருவாக்கியவர்',
    privacy: 'தனியுரிமை',
    test_notif: 'அறிவிப்பு சோதனை',
    reset_app: 'App மீட்டமை',
    reset_confirm: 'எல்லா data-யும் delete ஆகும். Sure-ஆ?',
    saved_success: 'சுயவிவரம் புதுப்பிக்கப்பட்டது!',
    remove: 'நீக்கு',
    done: 'முடிந்தது ✓',
    change: 'மாற்று →',
  },
};

export const t = (language, key) => {
  const lang = language === 'tamil' ? 'tamil' : 'english';
  return strings[lang][key] || strings['english'][key] || key;
};